# Generated by Django 5.2.5 on 2025-08-26 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('research_assistant', '0002_alter_researchassistant_department_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'main'), ('backup', 'backup')], max_length=20)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exam_assignments', to='exam.exam')),
                ('research_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exam_assingnments', to='research_assistant.researchassistant')),
            ],
        ),
    ]
