# Generated by Django 5.2.5 on 2025-08-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_assignment',
            old_name='exam_id',
            new_name='exam',
        ),
    ]
