# Generated by Django 5.2.5 on 2025-08-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('exam_assignment', '0002_rename_exam_id_exam_assignment_exam'),
        ('research_assistant', '0002_alter_researchassistant_department_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_assignment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='exam.exam'),
        ),
        migrations.AlterField(
            model_name='exam_assignment',
            name='research_assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assingnments', to='research_assistant.researchassistant'),
        ),
    ]
