# Generated by Django 5.2.5 on 2025-08-22 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('research_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchassistant',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='department.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
