# Generated by Django 5.2.5 on 2025-08-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_assistant', '0002_alter_researchassistant_department_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchassistant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
