# Generated by Django 5.2.5 on 2025-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
