# Generated by Django 5.2.5 on 2025-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Compute Engineering', 'Computer Engineering'), ('Electronic Engineering', 'Electronic Engineering')], max_length=100),
        ),
    ]
